[project]
name = "assignment-template"
version = "1.0.0"
requires-python= ">=3.11"
dependencies = [
    "gatorgrade",
    "mockro",
    "mypy>=1.19.1",
    "pytest",
]

[tool.pytest.ini_options]
pythonpath = [
    "src"
]
testpaths = [
    "tests"
]
filterwarnings = [
    "ignore::pytest.PytestAssertRewriteWarning"
]

[tool.mypy]
ignore_missing_imports = true
